### ISSUE TITLE
About the XMediaNet files in BaiduYun Link

### ISSUE THREAD

**Issue by Elfenreigen** [PKU-ICST-MIPL/RCBT_TCSVT2020#1]
Hello, I wonder whether the files in the BaiduYun link are the global representations extracted from pre-trained model VGGNet and word-CNN? cuz the dimensions of these vectors don't follow the implementation details in the paper? For example, the dimensions of the features of images should be 4,096, while those of vectors in the files is 25,088? Thank you.

**Comment by PKU-ICST-MIPL** [comment]
Thanks for your interest in our work.  The feature in BaiduYun Link is the 7*7*512 vectors from pool5 for LSTM, you can obtain more details from the 'load_all_lstm_feature_for_train' in utils.py.
